# Generated by Django 6.1 on 2026-08-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='risk_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='risk_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='risk_status',
            field=models.CharField(choices=[('pending', 'Pending review'), ('clear', 'Clear'), ('flagged', 'Flagged')], default='clear', max_length=10),
        ),
    ]
